apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app example to provide current timestamp
  annotations:
    github.com/project-slug: satish-bsvnuk/python-app
spec:
  type: service
  owner: development
  lifecycle: experimental
